import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import test from 'node:test';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const cycleScript = path.join(root, 'scripts', 'test-cycle-artifact.mjs');
const runCiPath = path.join(root, 'scripts', 'run-ci.mjs');
const workflowPath = path.join(root, '.github', 'workflows', 'ci.yml');
const versioningDocPath = path.join(root, 'docs', 'DEVELOPMENT-VERSIONING.md');
const agentRulesPath = path.join(root, 'AI_AGENT_RULES.md');
const artifactPath = 'chatgpt-conversation-markdown-export.user.js';

function git(cwd, args) {
  return execFileSync('git', args, { cwd, encoding: 'utf8' }).trim();
}

function runCycle(cwd, command, branch = 'issue-9-fixture', extraArgs = []) {
  return spawnSync(
    process.execPath,
    [cycleScript, command, '--branch', branch, ...extraArgs],
    { cwd, encoding: 'utf8' }
  );
}

async function createFixture() {
  const fixtureRoot = await mkdtemp(path.join(tmpdir(), 'downloadconversation-test-cycle-'));
  const remoteRoot = `${fixtureRoot}-remote.git`;
  await mkdir(path.join(fixtureRoot, 'src'), { recursive: true });
  await mkdir(path.join(fixtureRoot, 'scripts'), { recursive: true });

  await writeFile(
    path.join(fixtureRoot, 'src', 'userscript-header.js'),
    '// ==UserScript==\n// @version      1.2.0-issue.9.1\n// ==/UserScript==\n'
  );
  await writeFile(
    path.join(fixtureRoot, 'scripts', 'build-userscript.mjs'),
    [
      "import { readFile, writeFile } from 'node:fs/promises';",
      "const artifact = 'chatgpt-conversation-markdown-export.user.js';",
      "const header = await readFile('src/userscript-header.js', 'utf8');",
      "const built = `${header}console.log('fixture');\\n`;",
      "if (process.argv.includes('--check')) {",
      "  const existing = await readFile(artifact, 'utf8').catch(() => '');",
      "  if (existing !== built) {",
      "    console.error('Generated userscript is stale.');",
      "    process.exitCode = 1;",
      "  }",
      "} else {",
      "  await writeFile(artifact, built);",
      "}",
      ''
    ].join('\n')
  );

  git(fixtureRoot, ['init', '-b', 'issue-9-fixture']);
  git(fixtureRoot, ['config', 'user.name', 'Fixture User']);
  git(fixtureRoot, ['config', 'user.email', 'fixture@example.invalid']);
  git(fixtureRoot, ['add', 'src/userscript-header.js', 'scripts/build-userscript.mjs']);
  git(fixtureRoot, ['commit', '-m', 'fixture source']);
  execFileSync('git', ['init', '--bare', remoteRoot], { encoding: 'utf8' });
  git(fixtureRoot, ['remote', 'add', 'origin', remoteRoot]);
  git(fixtureRoot, ['push', '-u', 'origin', 'issue-9-fixture']);

  return { fixtureRoot, remoteRoot };
}

async function withFixture(callback) {
  const { fixtureRoot, remoteRoot } = await createFixture();
  try {
    await callback(fixtureRoot, remoteRoot);
  } finally {
    await rm(fixtureRoot, { recursive: true, force: true });
    await rm(remoteRoot, { recursive: true, force: true });
  }
}

test('test-cycle artifact publisher exposes prepare, verify, publish, and CI prepare-push commands', async () => {
  const source = await readFile(cycleScript, 'utf8');
  assert.match(source, /\bprepare\b/);
  assert.match(source, /\bverify\b/);
  assert.match(source, /\bpublish\b/);
  assert.match(source, /--push/);
  assert.match(source, /v\$\{version\}/);
  assert.match(source, /git[\s\S]*push[\s\S]*--atomic/);
});

test('prepare materializes and commits the exact generated artifact before tests', async () => {
  await withFixture(async fixtureRoot => {
    const before = git(fixtureRoot, ['rev-parse', 'HEAD']);
    const result = runCycle(fixtureRoot, 'prepare');
    assert.equal(result.status, 0, result.stderr || result.stdout);

    const after = git(fixtureRoot, ['rev-parse', 'HEAD']);
    assert.notEqual(after, before, 'prepare must create an artifact commit when generated bytes are absent');
    assert.equal(git(fixtureRoot, ['ls-files', '--error-unmatch', artifactPath]), artifactPath);
    assert.equal(git(fixtureRoot, ['status', '--porcelain']), '');
    assert.match(git(fixtureRoot, ['log', '-1', '--pretty=%s']), /materialize 1\.2\.0-issue\.9\.1/);
    assert.match(git(fixtureRoot, ['log', '-1', '--pretty=%s']), /\[skip ci\]/);

    const artifact = await readFile(path.join(fixtureRoot, artifactPath), 'utf8');
    assert.match(artifact, /@version\s+1\.2\.0-issue\.9\.1/);
  });
});

test('CI prepare-push publishes one shared artifact commit before test fan-out', async () => {
  await withFixture(async (fixtureRoot, remoteRoot) => {
    const result = runCycle(fixtureRoot, 'prepare', 'issue-9-fixture', ['--push']);
    assert.equal(result.status, 0, result.stderr || result.stdout);
    const preparedHead = git(fixtureRoot, ['rev-parse', 'HEAD']);
    const remoteHead = execFileSync(
      'git',
      ['--git-dir', remoteRoot, 'rev-parse', 'refs/heads/issue-9-fixture'],
      { encoding: 'utf8' }
    ).trim();
    assert.equal(remoteHead, preparedHead);
  });
});

test('verify fails closed when the committed artifact is stale', async () => {
  await withFixture(async fixtureRoot => {
    const prepared = runCycle(fixtureRoot, 'prepare');
    assert.equal(prepared.status, 0, prepared.stderr || prepared.stdout);

    await writeFile(path.join(fixtureRoot, artifactPath), 'stale artifact\n');
    git(fixtureRoot, ['add', artifactPath]);
    git(fixtureRoot, ['commit', '-m', 'make artifact stale']);

    const result = runCycle(fixtureRoot, 'verify');
    assert.notEqual(result.status, 0);
    assert.match(`${result.stdout}\n${result.stderr}`, /stale|deterministic|current/i);
  });
});

test('publish creates immutable version tag on the exact tested artifact commit', async () => {
  await withFixture(async (fixtureRoot, remoteRoot) => {
    const prepared = runCycle(fixtureRoot, 'prepare');
    assert.equal(prepared.status, 0, prepared.stderr || prepared.stdout);
    const testedHead = git(fixtureRoot, ['rev-parse', 'HEAD']);

    const published = runCycle(fixtureRoot, 'publish');
    assert.equal(published.status, 0, published.stderr || published.stdout);

    const localTagTarget = git(fixtureRoot, ['rev-list', '-n', '1', 'v1.2.0-issue.9.1']);
    assert.equal(localTagTarget, testedHead);
    const remoteTagTarget = execFileSync(
      'git',
      ['--git-dir', remoteRoot, 'rev-list', '-n', '1', 'v1.2.0-issue.9.1'],
      { encoding: 'utf8' }
    ).trim();
    assert.equal(remoteTagTarget, testedHead);
    const remoteBranchTarget = execFileSync(
      'git',
      ['--git-dir', remoteRoot, 'rev-parse', 'refs/heads/issue-9-fixture'],
      { encoding: 'utf8' }
    ).trim();
    assert.equal(remoteBranchTarget, testedHead);
  });
});

test('publish refuses to move an existing version tag to a later commit', async () => {
  await withFixture(async fixtureRoot => {
    assert.equal(runCycle(fixtureRoot, 'prepare').status, 0);
    assert.equal(runCycle(fixtureRoot, 'publish').status, 0);

    await writeFile(path.join(fixtureRoot, 'notes.txt'), 'later commit, same version\n');
    git(fixtureRoot, ['add', 'notes.txt']);
    git(fixtureRoot, ['commit', '-m', 'later same-version commit']);

    const result = runCycle(fixtureRoot, 'publish');
    assert.notEqual(result.status, 0);
    assert.match(`${result.stdout}\n${result.stderr}`, /tag.*different|different.*tag|version.*already/i);
  });
});

test('local and GitHub CI use the same test-cycle artifact contract', async () => {
  const runCi = await readFile(runCiPath, 'utf8');
  const workflow = await readFile(workflowPath, 'utf8');

  const prepareIndex = runCi.indexOf("['scripts/test-cycle-artifact.mjs', 'prepare'");
  const firstOrdinaryTest = runCi.indexOf('Modular userscript build regression');
  const publishIndex = runCi.lastIndexOf("['scripts/test-cycle-artifact.mjs', 'publish'");
  assert.ok(prepareIndex >= 0 && prepareIndex < firstOrdinaryTest, 'local CI must prepare artifact first');
  assert.ok(publishIndex > firstOrdinaryTest, 'local CI must publish only after tests');
  assert.match(runCi, /failures\.length === 0[\s\S]*test-cycle-artifact\.mjs[\s\S]*publish/);

  const prepareJob = workflow.indexOf('  prepare-test-cycle:');
  const prepareCommand = workflow.indexOf('node scripts/test-cycle-artifact.mjs prepare', prepareJob);
  const testJob = workflow.indexOf('  test:');
  assert.ok(prepareJob >= 0 && prepareCommand > prepareJob && prepareCommand < testJob);
  assert.match(workflow.slice(prepareJob, testJob), /--push/);
  assert.match(workflow.slice(prepareJob, testJob), /tested_sha/);
  assert.match(workflow.slice(prepareJob, testJob), /contents: write/);

  const firstVerify = workflow.indexOf('node scripts/test-cycle-artifact.mjs verify', testJob);
  const firstFeatureTest = workflow.indexOf('Modular userscript build regression', testJob);
  assert.ok(firstVerify > testJob && firstVerify < firstFeatureTest, 'CI test job must verify prepared artifact first');
  assert.match(workflow.slice(testJob, workflow.indexOf('  cross-consumer-final-render:')), /needs: prepare-test-cycle/);
  assert.match(workflow.slice(testJob, workflow.indexOf('  cross-consumer-final-render:')), /tested_sha/);

  const crossJob = workflow.indexOf('  cross-consumer-final-render:');
  const crossVerify = workflow.indexOf('node scripts/test-cycle-artifact.mjs verify', crossJob);
  const crossFeatureTest = workflow.indexOf('Install DownloadConversation AIConversationCore dependencies', crossJob);
  assert.ok(crossVerify > crossJob && crossVerify < crossFeatureTest, 'cross-consumer CI must verify prepared artifact first');
  assert.match(workflow.slice(crossJob, workflow.indexOf('  publish-test-cycle:')), /needs: prepare-test-cycle/);
  assert.match(workflow.slice(crossJob, workflow.indexOf('  publish-test-cycle:')), /tested_sha/);

  assert.match(workflow, /publish-test-cycle:/);
  assert.match(workflow, /needs:\s*\n\s*- prepare-test-cycle\s*\n\s*- test\s*\n\s*- cross-consumer-final-render/);
  assert.match(workflow, /node scripts\/test-cycle-artifact\.mjs publish/);
  assert.match(workflow, /contents: write/);
});

test('durable rules state that a validated generated artifact is committed and tagged automatically', async () => {
  const documentation = await readFile(versioningDocPath, 'utf8');
  const rules = await readFile(agentRulesPath, 'utf8');

  assert.match(documentation, /test cycle[\s\S]*committed[\s\S]*tagged|committed[\s\S]*tagged[\s\S]*test cycle/i);
  assert.match(documentation, /v<version>|v\$\{version\}|vX\.Y\.Z-issue/i);
  assert.match(rules, /test cycle[\s\S]*artifact[\s\S]*commit[\s\S]*tag/i);
  assert.match(rules, /repository-enforced|automatic/i);
});
